apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ldap
spec:
  template:
    spec:
      volumes:
        - name: ldap-data
          emptyDir: null
          gcePersistentDisk:
            pdName: ldap-persistent-storage
